sudo: required

language: cpp

compiler:
  - gcc


env:
  - TRAVIS_TAG=$MAJOR_VERSION.$MINOR_VERSION

branches:
  only:
    - master
    
before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb

install:
  - sudo /opt/devkitpro/pacman/bin/pacman -S $(sudo /opt/devkitpro/pacman/bin/pacman -Ssq switch-*) --noconfirm

script: make clean && make dist

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: 
    - "libnx-engine.tar.bz2"
    - "libnx-engine-src.tar.bz2"

  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
