sudo: required

language: cpp

compiler:
  - gcc

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb

install: ci/install_dependencies.sh

script: make clean && make all

notifications:
  email:
    on_success: never
